# Generated by Django 3.0.2 on 2020-01-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200125_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='DEFAULT DESCRIPTION', max_length=5000),
        ),
    ]
