# Generated by Django 3.0.2 on 2020-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200125_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='DEFAULT DESCRIPTION'),
        ),
    ]
